# Site settings
baseurl = "https://sunilanthony.github.io/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Sunil Anthony Blog"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "your_google_analytics_code"
hasCJKLanguage = true

[params]
	name = "Sunil Anthony"
	description = "Programming on the Microsoft .NET framework with C#."
	bio = ".NET Full-Stack Developer"
	# Enter optionally your twitter account
	twitter = "zXSwordXz"
	enableRSS = false

	# Disqus comment
	disqusShortname = "sunilanthony-com"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = true

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = false

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	tags = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I is not a bug, it is a undocumented feature."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
  linkedin-square = "https://www.linkedin.com/in/sunil-anthony-80765b11/"
  twitter-square = "https://twitter.com/zXSwordXz"
  github-square = "https://github.com/SunilAnthony"
  stack-overflow = "https://stackoverflow.com/users/5500031/zanthony"
